name: ExtraFurnaces
main: org.dyndns.pamelloes.ExtraFurnaces.ExtraFurnaces
version: 1.2.3
description: ExtraFurnaces uses the magic of Spout to add iron, gold, and diamond furnaces.
website: http://forums.getspout.org/threads/287/
depend: [Spout]